---

zookeeper:
  client_port: 2181
  connect_port: 2888
  conf_dir: /etc/zookeeper
  data_dir: /var/lib/zookeeper
  install_dir: /usr/share/zookeeper
  election_port: 3888
  user: zookeeper
  group: zookeeper
  hosts:
    - localhost
  id: 1
  java_opts: "-Xmx{{ (ansible_memtotal_mb / 2) | int }}m -Xms{{ (ansible_memtotal_mb / 2) | int }}m"
  # note this is for application logs, not the actual zookeeper data logs
  log_dir: /var/log/zookeeper
  log_level: WARN
  version: 3.4.8