---
- hosts: all
  vars:
  - remote_user: root
  tasks:
  - name: add confluent apt key
    become: True
    apt_key:
      url: http://packages.confluent.io/deb/3.1/archive.key
      state: present
  - name: update apt repository with confluent source.
    become: True
    apt_repository:
      repo:  deb [arch=amd64] http://packages.confluent.io/deb/3.1 stable main
      state: present
  - name: install confluent
    become: True
    apt:
      name: confluent-platform-oss-2.11
      state: latest
      update-cache: yes
